version: '3.5'
services:
  server:
    image: jwilford/tmodloader-server
    volumes:
      - terraria:/var/lib/terraria/
    ports:
      - 7777:7777
    networks:
      - proxy
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
networks:
  proxy:
    external: true
volumes:
  terraria:
    external: true